.\" $Id$
.\"
.\" Copyright (c) 2007 Nicholas Marriott <nicm@users.sourceforge.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
.\" IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: March 25 2013 $
.Dt TMUX 1
.Os
.Sh tmux
.Nm tmux
.Nd Key Bindings
.Pp
.Bl -tag -width "XXXXXXXXXX" -offset indent -compact
.It C-b
Send the prefix key (C-b) through to the application.
.It C-z
Suspend the
.Nm
client.
.It C-o
Rotate the panes in the current window forwards.
.It !
Break the current pane out of the window.
.It \&"
Split the current pane into two, top and bottom.
.It %
Split the current pane into two, left and right.
.It ;
Move to the previously active pane.
.It o
Select the next pane in the current window.
.It q
Briefly display pane indexes.
.It x
Kill the current pane.
.It {
Swap the current pane with the previous pane.
.It }
Swap the current pane with the next pane.
.It Up, Down
.It Left, Right
Change to the pane above, below, to the left, or to the right of the current
pane.
.It M-1 to M-5
Arrange panes in one of the five preset layouts: even-horizontal,
even-vertical, main-horizontal, main-vertical, or tiled.
.It M-o
Rotate the panes in the current window backwards.
.It C-Up, C-Down
.It C-Left, C-Right
Resize the current pane in steps of one cell.
.It M-Up, M-Down
.It M-Left, M-Right
Resize the current pane in steps of five cells.
.It &
Kill the current window.
.It '
Prompt for a window index to select.
.It ,
Rename the current window.
.It .
Prompt for an index to move the current window.
.It 0 to 9
Select windows 0 to 9.
.It c
Create a new window.
.It i
Display some information about the current window.
.It l
Move to the previously selected window.
.It n
Change to the next window.
.It p
Change to the previous window.
.It w
Choose the current window interactively.
.It M-n
Move to the next window with a bell or activity marker.
.It M-p
Move to the previous window with a bell or activity marker.
.It -
Delete the most recently copied buffer of text.
.It #
List all paste buffers.
.It =
Choose which buffer to paste interactively from a list.
.It \&[
Enter copy mode to copy text or view the history.
.It \&]
Paste the most recently copied buffer of text.
.It Page Up
Enter copy mode and scroll one page up.
.It $
Rename the current session.
.It D
Choose a client to detach.
.It d
Detach the current client.
.It s
Select a new session for the attached client interactively.
.It L
Switch the attached client back to the last session.
.It f
Prompt to search for text in open windows.
.It r
Force redraw of the attached client.
.It t
Show the time.
.It :
Enter the
.Nm
command prompt.
.It \&?
List all key bindings.
.It ~
Show previous messages from
.Nm ,
if any.
.El
